import { useMemo } from 'react';
import { usePartyStore } from '../store/partyStore';
import { Party, PartyTransaction } from '../types';
import { formatRupees } from '../lib/utils';

/**
 * Hook to manage Parties with derived data.
 * Party transactions are isolated from the Cashbook.
 * Only QR/Pay button payments go to Cashbook.
 */
export function useParties() {
  const {
    parties,
    partyTransactions,
    addParty,
    updateParty,
    deleteParty,
    addPartyTransaction,
    deletePartyTransaction,
    settleParty,
    getTransactionsForParty,
  } = usePartyStore();

  /** All active (non-deleted) parties */
  const activeParties = useMemo(
    () => parties.filter((p) => !p.isDeleted),
    [parties]
  );

  /** Customers — people who owe you (type = 'customer') */
  const customers = useMemo(
    () => activeParties.filter((p) => p.type === 'customer'),
    [activeParties]
  );

  /** Suppliers — people you owe (type = 'supplier') */
  const suppliers = useMemo(
    () => activeParties.filter((p) => p.type === 'supplier'),
    [activeParties]
  );

  /** Total you will get (sum of positive balances across all parties) */
  const totalToGet = useMemo(
    () =>
      activeParties
        .filter((p) => p.balance > 0)
        .reduce((sum, p) => sum + p.balance, 0),
    [activeParties]
  );

  /** Total you will give (sum of absolute negative balances across all parties) */
  const totalToGive = useMemo(
    () =>
      activeParties
        .filter((p) => p.balance < 0)
        .reduce((sum, p) => sum + Math.abs(p.balance), 0),
    [activeParties]
  );

  /** Net balance (totalToGet - totalToGive) */
  const netBalance = useMemo(() => totalToGet - totalToGive, [totalToGet, totalToGive]);

  /**
   * Get a party by ID.
   */
  const getParty = (id: string): Party | undefined =>
    parties.find((p) => p.id === id && !p.isDeleted);

  /**
   * Get active transactions for a party, sorted newest first.
   */
  const getPartyTransactions = (partyId: string): PartyTransaction[] =>
    partyTransactions
      .filter((t) => t.partyId === partyId && !t.isDeleted)
      .sort((a, b) => b.timestamp - a.timestamp);

  /**
   * Get the last activity timestamp for a party.
   */
  const getLastActivity = (partyId: string): number | null => {
    const txs = getPartyTransactions(partyId);
    return txs.length > 0 ? txs[0].timestamp : null;
  };

  /**
   * Generate a plain-text statement for a party (for sharing).
   */
  const generateStatement = (partyId: string): string => {
    const party = getParty(partyId);
    if (!party) return '';

    const txs = getPartyTransactions(partyId);
    const lines: string[] = [
      `--- FINZO Statement ---`,
      `Party: ${party.name}`,
      `Type: ${party.type === 'customer' ? 'Customer' : 'Supplier'}`,
      ``,
    ];

    for (const tx of txs.reverse()) {
      const date = new Date(tx.timestamp).toLocaleDateString('en-IN', {
        day: 'numeric',
        month: 'short',
        year: 'numeric',
      });
      const typeLabel = tx.type === 'give' ? 'GAVE' : 'GOT';
      const amountStr = formatRupees(tx.amount);
      const note = tx.note ? ` — ${tx.note}` : '';
      const settlement = tx.isSettlement ? ' [Settlement]' : '';
      lines.push(`${date} | ${typeLabel} ${amountStr}${note}${settlement}`);
    }

    lines.push('');
    if (party.balance > 0) {
      lines.push(`Balance: They owe you ${formatRupees(party.balance)}`);
    } else if (party.balance < 0) {
      lines.push(
        `Balance: You owe them ${formatRupees(Math.abs(party.balance))}`
      );
    } else {
      lines.push('Balance: Settled');
    }

    lines.push(``, `Generated by FINZO`);
    return lines.join('\n');
  };

  return {
    activeParties,
    customers,
    suppliers,
    totalToGet,
    totalToGive,
    netBalance,
    addParty,
    updateParty,
    deleteParty,
    addPartyTransaction,
    deletePartyTransaction,
    settleParty,
    getParty,
    getPartyTransactions,
    getLastActivity,
    generateStatement,
  };
}
